### PR TITLE
Add support for addLocation and noLocation gettext options

### PR DESCRIPTION
**Pull request by frontendphil**
I added the following config options

| name | default | description |
| --- | --- | --- |
| addLocation | `full` | Add a comment where the `msgid` was found. Options are: `full`, `file` and `never` |
| noLocation | false | Suppress adding location information altogether. Same as `addLocation: never` |

### CODE REVIEW

**Comment by frontendphil** [comment]
test this please

**Comment by TimKam** [comment]
Can you either ping me after the review passed or ensure the changes work in the context of the Process Manager?

**Comment by frontendphil** [comment]
test this please

**Comment by jfschwarz** [comment]
test this please

**Comment by frontendphil** [comment]
I've got to fix the test setup. Gonna do this tomorrow.

Sent from my iPhone

On 5 Apr 2017, at 09:40, Jan-Felix <notifications@github.com> wrote:

test this please

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/signavio/i18n/pull/15#issuecomment-291780181>, or mute
the thread

**Comment by frontendphil** [comment]
test this please

**Comment by frontendphil** [comment]
@TimKam merged and released as `1.3.0`. Changes do not affect current API. Hence no effects are expected.

**Pull request merged**
