### PR TITLE
Fixed pluralization issue

### PR DESCRIPTION
**Pull request by sobolev-alexey**
Fix for https://github.com/signavio/i18n/issues/18

### CODE REVIEW

**Comment by frontendphil** [comment]
Please also add tests for this.

**Comment by sobolev-alexey** [comment]
Added tests

**Comment by sobolev-alexey** [comment]
@jfschwarz could you please release a new version 1.3.2 with this change?

**Comment by jfschwarz** [comment]
@sobolev-alexey done.

**Pull request merged**
